version     = "0.1.0"
author      = "Softmax"
description = "Twenty pistons, one ball, nobody sees more than their neighbours."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.4"
requires "bitworld >= 0.1.0"
requires "pixie"
requires "mummy >= 0.4.7"
requires "curly >= 1.1.1"
requires "supersnappy >= 2.1.3"
requires "flatty >= 0.3.4"
requires "whisky >= 0.1.3"
